---
- name: Get information about vCenter
  vmware_about_info:
    hostname: "{{ vcenter.hostname }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    port: "{{ vcenter.port }}"
    validate_certs: no
  register: _vmware_about_info_vcenter

- name: Show information about vcenter
  debug:
    msg: "{{ _vmware_about_info_vcenter }}"

- name: Get information about ESXi servers
  vmware_about_info:
    hostname: "{{ esxi_hostname }}"
    username: "{{ esxi.username }}"
    password: "{{ esxi.password }}"
    validate_certs: no
  register: _vmware_about_info_esxi
  loop: "{{ esxi.hostnames }}"
  loop_control:
    loop_var: esxi_hostname

- name: Show information about vcenter
  debug:
    msg: "{{ _vmware_about_info_esxi }}"