---
- name: Add ESXi servers to vCenter
  vmware_host:
    hostname: "{{ vcenter.hostname }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter.name }}"
    cluster_name: "{{ vcenter.cluster.name }}"
    esxi_hostname: "{{ esxi_hostname }}"
    esxi_username: "{{ esxi.username }}"
    esxi_password: "{{ esxi.password }}"
    add_connected: yes
    validate_certs: no
    state: present
  loop: "{{ esxi.hostnames }}"
  loop_control:
    loop_var: esxi_hostname