- name: Create VMs from templates
  vmware_guest:
    hostname: "{{ vcenter.hostname }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter.name }}"
    folder: "/{{ vcenter.datacenter.name }}/vm/{{ vcenter.datacenter.folder.vm }}"
    esxi_hostname: "{{ vm.esxi_hostname }}"
    name: "{{ vm.name }}"
    state: present
    template: "{{ vm.template }}"
    disk: "{{ vm.disk }}"
    hardware: "{{ vm.hardware }}"
    networks: "{{ vm.networks }}"
    validate_certs: no
    # wait_for_ip_address: yes
  loop: "{{ vms }}"
  loop_control:
    loop_var: vm