---
- name: Create cluster
  vmware_cluster:
    hostname: "{{ vcenter.hostname }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    port: "{{ vcenter.port }}"
    datacenter_name: "{{ vcenter.datacenter.name }}"
    cluster_name: "{{ vcenter.cluster.name }}"
    validate_certs: no
    state: present
