- name: Deploy VMs from ovf
  vmware_deploy_ovf:
    hostname: "{{ vcenter.hostname }}"
    username: "{{ vcenter.username }}"
    password: "{{ vcenter.password }}"
    datacenter: "{{ vcenter.datacenter.name }}"
    cluster: "{{ vcenter.cluster.name }}"
    folder: "/{{ vcenter.datacenter.name }}/vm/{{ vcenter.datacenter.folder.vm }}"
    name: "{{ vm_template.name }}"
    datastore: "{{ vm_template.datastore }}"
    ovf: "{{ vm_template.ovf }}"
    disk_provisioning: thin
    networks: "{{ vm_template.networks }}"
    allow_duplicates: no
    power_on: no
    validate_certs: no
  loop: "{{ vm_templates }}"
  loop_control:
    loop_var: vm_template


- name: Remove the Network Adapter
  command: >-
    govc device.remove
      -vm /{{ vcenter.datacenter.name }}/vm/{{ vcenter.datacenter.folder.vm }}/{{ vm_template.name }} ethernet-0
  environment:
    GOVC_URL: "{{ vcenter.hostname }}"
    GOVC_USERNAME: "{{ vcenter.username }}"
    GOVC_PASSWORD: "{{ vcenter.password }}"
    GOVC_INSECURE: true
  changed_when: no
  failed_when: no
  loop: "{{ vm_templates }}"
  loop_control:
    loop_var: vm_template

- name: Update VM options on the templates
  command: >-
    govc vm.change
      -vm /{{ vcenter.datacenter.name }}/vm/{{ vcenter.datacenter.folder.vm }}/{{ vm_template.name }}
      -latency high
      -e=disk.EnableUUID=TRUE
      -e=guestinfo.ignition.config.data.encoding=base64
      -e=guestinfo.ignition.config.data=blah
  environment:
    GOVC_URL: "{{ vcenter.hostname }}"
    GOVC_USERNAME: "{{ vcenter.username }}"
    GOVC_PASSWORD: "{{ vcenter.password }}"
    GOVC_INSECURE: true
  changed_when: no
  loop: "{{ vm_templates }}"
  loop_control:
    loop_var: vm_template